### ISSUE TITLE
Feature request: folder parameter for portfolio modal content

### ISSUE THREAD

**Issue by StuartJMackintosh** [mayamcdougall/freelancer-pico#6]
Portfolio by default includes pages that are in the root folder and not hidden. 

In the interest of organisation, I would like to create a subfolder for the portfolio items and modal content. 

Currently, if I create a page in the root, it just appears in the portfolio unless I take action to hide it.

With an option to override the folder, it becomes clear where items should be placed to be included.

For example:

```yaml
# Example Config
portfolio:
  title: Recent Projects
  divider: clock
  disable_close_buttons: true
  folder: /portfolio_pages
```
